import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import Navigation from "./_components/Navigation";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <main className="min-h-screen bg-gradient-to-br from-purple-700 via-blue-600 to-teal-400">
        <Navigation />
  
       <TRPCReactProvider>{children}</TRPCReactProvider>
  
        <footer className="container mx-auto px-4 py-6 mt-20 text-center text-teal-200">
          <p>&copy; 2025 Codetyhub AI App. All rights reserved.</p>
        </footer>
      </main>
      </body>
    </html>
  );
}
